### Post new BP
POST http://localhost:4004/api-business-partner/A_BusinessPartner
Content-Type: application/json

{
    "BusinessPartner":"123",
    "BusinessPartnerFullName":"ABCD Corp."
}

### Post new BP with address
POST https://<mockserver-url>/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
Content-Type: application/json

{
    "BusinessPartner":"2a312",
    "BusinessPartnerFullName":"ad Corp as",
    "FirstName": "GOPS",
    "SearchTerm1" : "EFVERIFIED"
}